### PR TITLE
Merge release 1.3.3 into 2.0

### PR DESCRIPTION
**Pull request by doctrinebot**
Release [1.3.3](https://github.com/doctrine/data-fixtures/milestone/13)

1.3.3
=====

- Total issues resolved: **0**
- Total pull requests resolved: **1**
- Total contributors: **1**

Improvement
-----------

 - [323: Fix travis build](https://github.com/doctrine/data-fixtures/pull/323) thanks to @alcaeus

### CODE REVIEW

**Comment by Ocramius** [comment]
This is obviously the "usual mess" - we haven't used merge-up strategy so far, so this patch is clear conflict with everything in the `2.0` branch

**Comment by Ocramius** [comment]
Note: branch `1.4.x` does not exist at this point in time, but many milestone items are already in it: need to discuss branching strategy on this particular repository.

**Comment by alcaeus** [comment]
2.0 had its last activity 2 years ago, so I'd say we disregard that for now. `master` currently is `1.4.x-dev` and has been used as such.

For the time being, I'd close this PR and re-analyse the 2.0 branch to see if we can pick up the work again.

**Comment by Ocramius** [comment]
Renaming `2.0` to `next` (both branch and milestone) could also make things more manageable for the time being

**Comment by alcaeus** [comment]
`2.0` branch re-pushed as `next` as to not confuse our bot. Closing here.

**Pull request closed without merging**
