### PR TITLE
Added some basic CLI

### PR DESCRIPTION
**Pull request by lsv**
# Command line interface (CLI)

You will need to edit a Doctrine file for this to work.
Goto
Doctrine/ORM/Tools/Console/ConsoleRunner.php

Add this

```
// Fixtures
new \Doctrine\Common\DataFixtures\Command\Add(),
```

after

```
new \Doctrine\ORM\Tools\Console\Command\InfoCommand(),
```

Now you can use

```
./doctrine fixtures:add
```
## Options to fixtures:add

```
--directory (-d) Directory with your fixtures - Its relative to your Entities\Proxies path *REQUIRED*
--append (-a) If you want to append your fixtures instead
--dump-fixtures Vieweing the fixtures instead of importing them
```

### CODE REVIEW

**Comment by lavoiesl** [comment]
Shouldn’t this command be called `fixtures:load` to avoid confusion?

**Comment by L0rD59** [comment]
:+1:

**Comment by halfpastfouram** [comment]
Has there been any progress with this, whatsoever? If not, I am more than willing to take on improving this PR until it is accepted.

**Comment by SenseException** [comment]
It doesn't look like @lsv is working further on it since it was created in 2012. If it is okay would you like to take over?

**Comment by halfpastfouram** [comment]
@SenseException I'd love to! I believe this PR will be a welcome addition.

**Pull request closed without merging**
