### PR TITLE
Version 2: Make executors and purgers final

### PR DESCRIPTION
**Pull request by dbu**
This is a follow up to #289 (and will show the changes from #289 until it is merged) to make purgers and executors final and add return type and method type declarations where possible. i also remove pointless phpdoc comments.

This bumps the version to 2 - i suggest to keep this open and wait with merging until you feel ready to start the 2.0 version.

### CODE REVIEW

**Comment by Ocramius** [comment]
Looking good from here. Something went completely sideways with `composer update` though. Also, do we want to stop improvements on the `1.x` series, @doctrine/doctrinecore?

**Comment by dbu** [comment]
i rebased on master, now the diff is better readable.

i just noticed that there is a 2.0 branch with lots of commits, but also way behind master... shall i change this MR to go against the 2.0 branch? shall i cherry-pick this change, or does somebody want to first merge master into 2.0 to have it more up to date?

or should we create a 1.3 maintenance branch from master and then merge 2.0 to master to get 2.0 rolling?

**Comment by Ocramius** [comment]
@dbu that depends on @guilhermeblanco: he worked a lot on fixtures 2.x, but we never got to push it through...

**Comment by derrabus** [comment]
Closing in favor of #458.

**Pull request closed without merging**
