### PR TITLE
Added support for self referencing classes in the TopologicalSorter

### LINKED ISSUE #228: TopologicalSorter breaks fixture load
The TopologicalSorter throws the error:

````
 Graph contains cyclic dependency. An example of this problem would be the following: Class C has class B as its dependency. Then, class B has class A has its dependency. Finally, class A has class C as its dependency. 
````

Everything was working before. As the error is not providing much information I will investigate further.

### PR DESCRIPTION
**Pull request by peterrehm**
A first solution to the issue #228. I don't know if this raises further issues.

- fixes #228

### CODE REVIEW

**Comment by Ocramius** [comment]
Requires tests

**Comment by peterrehm** [comment]
Just wanted to know if the general implementation makes sense. Then I can add a test.

**Comment by peterrehm** [comment]
@Ocramius Is that test case enough?

**Comment by Ocramius** [comment]
Seems good to me. @guilhermeblanco can you check this? I don't know if this follows your train of thought.

**Comment by guilhermeblanco** [comment]
Reviewed and LGTM. Merged

**Comment by NeilJ247** [comment]
Hi,

Not sure if this is the correct place to post if it isn't then let me know and I will raise as a new issue.  We are using Alice fixtures and still getting the same CircularReferenceException.  I was under the impression this was fixed in 1.2.1?  These are the versions for Alice fixtures and data-fixtures that we have been using:

        "hautelook/alice-bundle": "^1.3",
        "doctrine/data-fixtures": "^1.2",

Downgraded data-fixtures to 1.1 as a temporary fix within our project which doesn't give us the error.

Any help/feedback would be appreciated.

Thanks.

**Comment by peterrehm** [comment]
Did you try with dev-master to test https://github.com/doctrine/data-fixtures/pull/240?

**Comment by mikeSimonson** [comment]
I need to make a release. I will try to do that rapidly.

**Comment by NeilJ247** [comment]
@peterrehm Hi sorry for the delayed answer.  Yes I have tried with dev-master and it works.  I thought it was fixed in the current version.

**Comment by peterrehm** [comment]
@NeilJ247 There us a release peding by @mikeSimonson

**Comment by NeilJ247** [comment]
@peterrehm thanks.

**Pull request merged**
