### PR TITLE
[v2] Convert `@final` to hard `final`

### PR DESCRIPTION
**Pull request by GromNaN**
Follow-up #457

~Could you create the 2.0.x branch, please.~

### CODE REVIEW

**Comment by derrabus** [comment]
Can you look into the static analysis and test failures, please? 🙃

**Comment by GromNaN** [comment]
It's always an *interesting challenge* to get around the impossible task of mocking a final class.

**Comment by greg0ire** [comment]
> Could you create the 2.0.x branch, please.

Done

**Comment by greg0ire** [comment]
@GromNaN rebased… can you fix the remaining build issues?

**Pull request closed without merging**
