### PR TITLE
Changed the MongoDBPurger class to only clear collections

### LINKED ISSUE #150: Data Fixtures will destroy mongodb schema
Hello.

I wrote some fixtures for my app. I'm using mongodb. First I run the following command to prepare my database.

`php app/console doctrine:mongodb:schema:create`

> Created dbs for all classes
> Created collections for all classes
> Created indexes for all classes

Everything is perfect. Now I want to load my fixtures with the following command.

`php app/console doctrine:mongodb:fixtures:load`
> purging database
> loading [1] Acme\DemoBundle\DataFixtures\MongoDB\LoadUserData
> loading [2] Acme\DemoBundle\DataFixtures\MongoDB\LoadClientData

If I check my database schema, all fixtures are loaded successfully, but my indexes are dropped and this will result in a wrong behavior at database save statements.

I've to execute the command `php app/console doctrine:mongodb:schema:create` again and all indexes are back.

Is there a way to fix this? My fixtures are straight forward copy & paste from the documentation, no specials, no extras.

I'm using the `dev-master` version of both components.

```json
"doctrine/data-fixtures": "dev-master",
"doctrine/doctrine-fixtures-bundle": "dev-master"
```

Cheers.

### PR DESCRIPTION
**Pull request by gerryvdm**
Changed the MongoDBPurger class to only clear collections, not remove them.

Instead of dropping all collections, we should remove all documents in a
collection instead. This avoids problems where indexes are lost while dropping
the collection, and collections not being recreated (with a schema create tool)
while loading fixtures.

Fixes #150

### CODE REVIEW

**Comment by gerryvdm** [comment]
Do I need to reword this pull request? Been well over a year now... :)

**Comment by lavoiesl** [comment]
@gerryvdm, yes, please rebase your PR.

**Comment by lavoiesl** [comment]
@gerryvdm, I would like to be able to release this PR in 1.1 by tomorrow, do you think you would be able to care of it?

**Comment by lavoiesl** [comment]
Superseeded

**Pull request closed without merging**
