### PR TITLE
unidirectional-relation

### PR DESCRIPTION
**Pull request by dominikzogg**

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@dominikzogg What does that test try to show ?

**Comment by dominikzogg** [comment]
@mikeSimonson Without setting null users.role_id or delete the row, roles arent deletable even if its a unidirectional relation

**Comment by mikeSimonson** [comment]
@dominikzogg Can you add that in a comment on top of the test ?

**Comment by dominikzogg** [comment]
@mikeSimonson done

**Comment by mikeSimonson** [comment]
@dominikzogg Did you see that the test fails ?

**Comment by stof** [comment]
What is the issue you have exactly ? I don't understand which issue you try to solve

**Comment by dominikzogg** [comment]
@mikeSimonson as @stof mentioned, should i add a test or describe the whole scenario (which is not possible) the cleanup does not work. I my point of view, the code should be changed, that the test will run, cause at the moment unidirectional relations leads to trouble on data cleanup.

**Comment by dominikzogg** [comment]
sorry not @stof mentioned it, it was @Ocramius https://github.com/doctrine/data-fixtures/issues/230#issuecomment-227435471

**Pull request closed without merging**
