### PR TITLE
Don't try to purge embedded classes

### PR DESCRIPTION
**Pull request by ferodss**
Fix for #157

### CODE REVIEW

**Comment by lerox** [comment]
@ferodss +1

**Comment by leonardothibes** [comment]
@ferodss +1

**Comment by klaussilveira** [comment]
@stof, any news on this? There's a lot of people waiting for this fix on #157.

**Comment by guilhermeblanco** [comment]
@klaussilveira done... =)

**Comment by klaussilveira** [comment]
@guilhermeblanco :smiley:

**Comment by ferodss** [comment]
@guilhermeblanco :+1:

**Comment by Ocramius** [comment]
This diff breaks pre-2.5 installs: probably needs to be reverted.

**Comment by guilhermeblanco** [comment]
I wouldn't revert, but address it by checking if property exists.
Should do it in a few minutes

**Pull request merged**
